---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then pip install black; fi
  - pip install -r requirements/dev.txt
  # - python setup.py install

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      black --check --diff -l 79 *.py pycsco
    fi
  - yamllint .travis.yml
  # - flake8 *.py pycsco
  # - nosetests --with-coverage --cover-min-percentage=40
  #            --cover-package=pycsco --cover-inclusive
